/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'portfolio-categories': PortfolioCategory;
    'portfolio-items': PortfolioItem;
    'pricing-plans': PricingPlan;
    testimonials: Testimonial;
    faqs: Faq;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'portfolio-categories': PortfolioCategoriesSelect<false> | PortfolioCategoriesSelect<true>;
    'portfolio-items': PortfolioItemsSelect<false> | PortfolioItemsSelect<true>;
    'pricing-plans': PricingPlansSelect<false> | PricingPlansSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    branding: Branding;
    navigation: Navigation;
    footer: Footer;
    'owner-profile': OwnerProfile;
    'default-seo': DefaultSeo;
    'theme-settings': ThemeSetting;
    homepage: Homepage;
    'portfolio-page': PortfolioPage;
    'contact-page': ContactPage;
  };
  globalsSelect: {
    branding: BrandingSelect<false> | BrandingSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'owner-profile': OwnerProfileSelect<false> | OwnerProfileSelect<true>;
    'default-seo': DefaultSeoSelect<false> | DefaultSeoSelect<true>;
    'theme-settings': ThemeSettingsSelect<false> | ThemeSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'portfolio-page': PortfolioPageSelect<false> | PortfolioPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-categories".
 */
export interface PortfolioCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  displayOrder: number;
  status: 'draft' | 'published' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-items".
 */
export interface PortfolioItem {
  id: number;
  title: string;
  slug: string;
  category: number | PortfolioCategory;
  image?: (number | null) | Media;
  /**
   * Used for existing Supabase-hosted images during migration.
   */
  externalImageUrl?: string | null;
  shortDescription?: string | null;
  fullDescription?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  popularityScore?: number | null;
  clientName?: string | null;
  clientPermission?: boolean | null;
  externalLink?: string | null;
  orderLink?: string | null;
  displayOrder: number;
  status: 'draft' | 'published' | 'private';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans".
 */
export interface PricingPlan {
  id: number;
  name: string;
  slug: string;
  description: string;
  fullDescription?: string | null;
  price: number;
  currency?: 'USD' | null;
  deliveryTime?: string | null;
  revisions?: string | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  highlighted?: boolean | null;
  orderUrl?: string | null;
  displayOrder: number;
  status: 'draft' | 'published' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  clientName: string;
  clientRole?: string | null;
  quote: string;
  rating: number;
  featured?: boolean | null;
  displayOrder: number;
  status: 'draft' | 'published' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  displayOrder: number;
  status: 'draft' | 'published' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'portfolio-categories';
        value: number | PortfolioCategory;
      } | null)
    | ({
        relationTo: 'portfolio-items';
        value: number | PortfolioItem;
      } | null)
    | ({
        relationTo: 'pricing-plans';
        value: number | PricingPlan;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-categories_select".
 */
export interface PortfolioCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  displayOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-items_select".
 */
export interface PortfolioItemsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  image?: T;
  externalImageUrl?: T;
  shortDescription?: T;
  fullDescription?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featured?: T;
  popularityScore?: T;
  clientName?: T;
  clientPermission?: T;
  externalLink?: T;
  orderLink?: T;
  displayOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans_select".
 */
export interface PricingPlansSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  fullDescription?: T;
  price?: T;
  currency?: T;
  deliveryTime?: T;
  revisions?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  highlighted?: T;
  orderUrl?: T;
  displayOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  clientRole?: T;
  quote?: T;
  rating?: T;
  featured?: T;
  displayOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  displayOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding".
 */
export interface Branding {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  browserTitle?: string | null;
  logo?: (number | null) | Media;
  /**
   * Existing external logo URL.
   */
  logoUrl?: string | null;
  favicon?: (number | null) | Media;
  /**
   * Existing external favicon URL.
   */
  faviconUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  headerLinks?:
    | {
        label: string;
        href: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  mobileCta: {
    label: string;
    href: string;
    newTab?: boolean | null;
    id?: string | null;
  };
  adminLink: {
    enabled?: boolean | null;
    label: string;
    href: string;
    newTab?: boolean | null;
  };
  footerLinks?:
    | {
        label: string;
        href: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  brandKicker?: string | null;
  description?: string | null;
  ownerProfileNotice?: string | null;
  navigationHeading?: string | null;
  contactHeading?: string | null;
  primaryCta: {
    label: string;
    href: string;
    newTab?: boolean | null;
    id?: string | null;
  };
  secondaryCta: {
    label: string;
    href: string;
    newTab?: boolean | null;
    id?: string | null;
  };
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "owner-profile".
 */
export interface OwnerProfile {
  id: number;
  name: string;
  role?: string | null;
  biography?: string | null;
  location?: string | null;
  avatar?: (number | null) | Media;
  avatarUrl?: string | null;
  socialProfiles?:
    | {
        kind:
          | 'email'
          | 'discord'
          | 'discord_server'
          | 'instagram'
          | 'x'
          | 'youtube'
          | 'fiverr'
          | 'behance'
          | 'website'
          | 'github'
          | 'modrinth';
        label: string;
        value?: string | null;
        href: string;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "default-seo".
 */
export interface DefaultSeo {
  id: number;
  title?: string | null;
  description?: string | null;
  openGraphTitle?: string | null;
  openGraphDescription?: string | null;
  openGraphImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings".
 */
export interface ThemeSetting {
  id: number;
  preset: 'cosmicPurple' | 'midnightBlue' | 'crimson' | 'emerald' | 'custom';
  colors: {
    /**
     * Safe hex colors only. Arbitrary CSS is not accepted.
     */
    primary: string;
    /**
     * Safe hex colors only. Arbitrary CSS is not accepted.
     */
    primaryHover: string;
    /**
     * Safe hex colors only. Arbitrary CSS is not accepted.
     */
    primaryForeground: string;
    /**
     * Safe hex colors only. Arbitrary CSS is not accepted.
     */
    secondary: string;
    /**
     * Safe hex colors only. Arbitrary CSS is not accepted.
     */
    accent: string;
    /**
     * Safe hex colors only. Arbitrary CSS is not accepted.
     */
    background: string;
    /**
     * Safe hex colors only. Arbitrary CSS is not accepted.
     */
    backgroundAlternate: string;
    /**
     * Safe hex colors only. Arbitrary CSS is not accepted.
     */
    surface: string;
    /**
     * Safe hex colors only. Arbitrary CSS is not accepted.
     */
    surfaceElevated: string;
    /**
     * Safe hex colors only. Arbitrary CSS is not accepted.
     */
    textPrimary: string;
    /**
     * Safe hex colors only. Arbitrary CSS is not accepted.
     */
    textMuted: string;
    /**
     * Safe hex colors only. Arbitrary CSS is not accepted.
     */
    border: string;
    /**
     * Safe hex colors only. Arbitrary CSS is not accepted.
     */
    glow: string;
    /**
     * Safe hex colors only. Arbitrary CSS is not accepted.
     */
    focusRing: string;
  };
  radiusPreset?: ('small' | 'medium' | 'large' | 'extra-large') | null;
  shadowIntensity?: ('none' | 'subtle' | 'medium' | 'strong') | null;
  glowIntensity?: ('none' | 'subtle' | 'medium' | 'strong') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    badge?: string | null;
    heading?: string | null;
    description?: string | null;
    primaryCta: {
      label: string;
      href: string;
      newTab?: boolean | null;
      id?: string | null;
    };
    secondaryCta: {
      label: string;
      href: string;
      newTab?: boolean | null;
      id?: string | null;
    };
    statistics?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  featuredWork: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    cta: {
      label: string;
      href: string;
      newTab?: boolean | null;
      id?: string | null;
    };
    autoplayDelayMs?: number | null;
  };
  ownerProfilePresentation: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    cta: {
      label: string;
      href: string;
      newTab?: boolean | null;
      id?: string | null;
    };
  };
  servicesPresentation?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    countSuffix?: string | null;
    cardCtaLabel?: string | null;
  };
  testimonialsPresentation?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    statistics?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  pricingPresentation: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    highlightBadge?: string | null;
    priceSuffix?: string | null;
    moreFeaturesLabel?: string | null;
    planCtaLabel?: string | null;
    customPackageHeading?: string | null;
    customPackageFallbackKicker?: string | null;
    customPackageOwnerKickerTemplate?: string | null;
    customPackageDescription?: string | null;
    customPackageCta: {
      label: string;
      href: string;
      newTab?: boolean | null;
      id?: string | null;
    };
  };
  faqPresentation: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    ctaKicker?: string | null;
    cta: {
      label: string;
      href: string;
      newTab?: boolean | null;
      id?: string | null;
    };
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    openGraphTitle?: string | null;
    openGraphDescription?: string | null;
    openGraphImage?: (number | null) | Media;
    updatedAt?: string | null;
    createdAt?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-page".
 */
export interface PortfolioPage {
  id: number;
  filterHeading?: string | null;
  allCategoriesLabel?: string | null;
  sortHeading?: string | null;
  sortOptions?:
    | {
        id: string;
        label: string;
      }[]
    | null;
  eyebrow?: string | null;
  heading?: string | null;
  workSingular?: string | null;
  workPlural?: string | null;
  categorySuffix?: string | null;
  emptyState?: string | null;
  featuredBadge?: string | null;
  cardCtaLabel?: string | null;
  modalEyebrow?: string | null;
  categoryLabel?: string | null;
  dateLabel?: string | null;
  descriptionLabel?: string | null;
  tagsLabel?: string | null;
  modalCta: {
    label: string;
    href: string;
    newTab?: boolean | null;
    id?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    openGraphTitle?: string | null;
    openGraphDescription?: string | null;
    openGraphImage?: (number | null) | Media;
    updatedAt?: string | null;
    createdAt?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  seoTitleTemplate?: string | null;
  seoFallbackDescription?: string | null;
  eyebrow?: string | null;
  headingTemplate?: string | null;
  description?: string | null;
  ownerProfileEyebrow?: string | null;
  bioFallback?: string | null;
  discordServerDisplayFallback?: string | null;
  actions?:
    | {
        kind: string;
        platform: string;
        action: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    openGraphTitle?: string | null;
    openGraphDescription?: string | null;
    openGraphImage?: (number | null) | Media;
    updatedAt?: string | null;
    createdAt?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding_select".
 */
export interface BrandingSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  browserTitle?: T;
  logo?: T;
  logoUrl?: T;
  favicon?: T;
  faviconUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  mobileCta?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  adminLink?:
    | T
    | {
        enabled?: T;
        label?: T;
        href?: T;
        newTab?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandKicker?: T;
  description?: T;
  ownerProfileNotice?: T;
  navigationHeading?: T;
  contactHeading?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "owner-profile_select".
 */
export interface OwnerProfileSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  biography?: T;
  location?: T;
  avatar?: T;
  avatarUrl?: T;
  socialProfiles?:
    | T
    | {
        kind?: T;
        label?: T;
        value?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "default-seo_select".
 */
export interface DefaultSeoSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  openGraphTitle?: T;
  openGraphDescription?: T;
  openGraphImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings_select".
 */
export interface ThemeSettingsSelect<T extends boolean = true> {
  preset?: T;
  colors?:
    | T
    | {
        primary?: T;
        primaryHover?: T;
        primaryForeground?: T;
        secondary?: T;
        accent?: T;
        background?: T;
        backgroundAlternate?: T;
        surface?: T;
        surfaceElevated?: T;
        textPrimary?: T;
        textMuted?: T;
        border?: T;
        glow?: T;
        focusRing?: T;
      };
  radiusPreset?: T;
  shadowIntensity?: T;
  glowIntensity?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        heading?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
              newTab?: T;
              id?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
              newTab?: T;
              id?: T;
            };
        statistics?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  featuredWork?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        description?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
              newTab?: T;
              id?: T;
            };
        autoplayDelayMs?: T;
      };
  ownerProfilePresentation?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        description?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
              newTab?: T;
              id?: T;
            };
      };
  servicesPresentation?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        description?: T;
        countSuffix?: T;
        cardCtaLabel?: T;
      };
  testimonialsPresentation?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        description?: T;
        statistics?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  pricingPresentation?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        description?: T;
        highlightBadge?: T;
        priceSuffix?: T;
        moreFeaturesLabel?: T;
        planCtaLabel?: T;
        customPackageHeading?: T;
        customPackageFallbackKicker?: T;
        customPackageOwnerKickerTemplate?: T;
        customPackageDescription?: T;
        customPackageCta?:
          | T
          | {
              label?: T;
              href?: T;
              newTab?: T;
              id?: T;
            };
      };
  faqPresentation?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        description?: T;
        ctaKicker?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
              newTab?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        openGraphTitle?: T;
        openGraphDescription?: T;
        openGraphImage?: T;
        updatedAt?: T;
        createdAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-page_select".
 */
export interface PortfolioPageSelect<T extends boolean = true> {
  filterHeading?: T;
  allCategoriesLabel?: T;
  sortHeading?: T;
  sortOptions?:
    | T
    | {
        id?: T;
        label?: T;
      };
  eyebrow?: T;
  heading?: T;
  workSingular?: T;
  workPlural?: T;
  categorySuffix?: T;
  emptyState?: T;
  featuredBadge?: T;
  cardCtaLabel?: T;
  modalEyebrow?: T;
  categoryLabel?: T;
  dateLabel?: T;
  descriptionLabel?: T;
  tagsLabel?: T;
  modalCta?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        openGraphTitle?: T;
        openGraphDescription?: T;
        openGraphImage?: T;
        updatedAt?: T;
        createdAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  seoTitleTemplate?: T;
  seoFallbackDescription?: T;
  eyebrow?: T;
  headingTemplate?: T;
  description?: T;
  ownerProfileEyebrow?: T;
  bioFallback?: T;
  discordServerDisplayFallback?: T;
  actions?:
    | T
    | {
        kind?: T;
        platform?: T;
        action?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        openGraphTitle?: T;
        openGraphDescription?: T;
        openGraphImage?: T;
        updatedAt?: T;
        createdAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}